# Phoenix Table Configuration Options
IS_STRICT_TTL=false
UPDATE_CACHE_FREQUENCY=60000
phoenix.max.lookback.age.seconds=97200
hbase.hregion.majorcompaction=172800000
org.apache.hadoop.hbase.index.lazy.post_batch.write=true
phoenix.index.cdc.consumer.batch.size=500
phoenix.index.cdc.mutation.serialize=false
phoenix.index.cdc.consumer.timestamp.buffer.ms=5000